### ISSUE TITLE
Transaction not displayed

### ISSUE THREAD

**Issue by karelbilek** [yogh-io/bitcoin-transaction-explorer#15]
I cannot find this transaction on yogh.io

https://btc1.trezor.io/tx/d276abe15791941649c3ca8425d79167cc1cf801f83aa99753fe7f42740c0f23

> This transaction does not exist in the blockchain and could not be found in the unconfirmed transaction pool.

[yogh.io link](http://yogh.io/#tx:id:d276abe15791941649c3ca8425d79167cc1cf801f83aa99753fe7f42740c0f23)

**Comment by Giszmo** [comment]
Broken link. [This one](https://www.smartbit.com.au/tx/d276abe15791941649c3ca8425d79167cc1cf801f83aa99753fe7f42740c0f23) works.

**Comment by karelbilek** [comment]
2017 :D still, bug persists.

**Comment by karelbilek** [comment]
I fixed the link though
